PRAISE

medium

# `_validateNewBorrowAsset()` function validation logic could throw an error, leading to the entire transaction failing. Manager won't be able to sort which borrow asset caused it due to lack of proper error handling

## Summary
in addBorrowAssets() function `_newBorrowAssets`  is an array of ERC20 tokens to be added as new borrow asset.

## Vulnerability Detail
i believe this is an issue because 
1. An already enabled borrow asset could be in the `_newBorrowAssets`  array.
2. A non-active or frozen borrow asset could be in the array too.

Now the main issue here is this-- manaager won't be able to trace the successfully added borrow assets and the asset which failed. 

Manager will have to rerun the TX but he won't be able  to trace which of the borrow assets caused the entire transaction to fail

## Impact
Manager won't be able to know the borrow assets that were successfully added and also he won't be able to trace which of the borrow assets that made the entire transaction fail in `_validateNewBorrowAsset()` 

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1004-L1014
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1120
## Tool used

Manual Review

## Recommendation
have the require statements in  `_validateNewBorrowAsset()` function emit the index/position of the borrow assets that caused the require statements to fail. 
That way manager will be able to trace and remove them before rerunning the transaction